server:
  prefix: /api
  port: 8050
  host: localhost
  verifyUrl: http://localhost:8050/api/guest/verify

service:
  root: .server
  imgDir: img
  thumbDir: thumb
  password: password

session:
  authKey: authKey
  encKey: encKey
  authKeyOld: authKeyOld
  encKeyOld: encKeyOld
  cookieName: server-session

db:
  host: localhost
  port: 5432
  user: mphotos_test
  password: mphotos_test
  name: mphotos-test

google:
  redirectUrl: http://some/redirect/url
  clientId: clientId
  clientSecret: clientSecret
