server:
  prefix: /api
  port: 8050
  host: localhost

service:
  root: .mphotos #default
  imgDir: img #image path
  thumbDir: thumb #thumbnail path
  password: password

session:
  authKey: authKey #64 bytes recommended
  encKey: encKey #32bytes recommended
  authKeyOld: authKeyOld
  encKeyOld: encKeyOld
  cookieName: mphotos-session


db:
  host: localhost
  port: 5432
  user: user
  password: password
  name: name

google:
  redirectUrl: http://some/redirect/url
  clientId: clientId
  clientSecret: clientSecret
